# Flex Gateway Authentication Policy
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: employee-onboarding-auth
  namespace: default
spec:
  targetRef:
    name: employee-onboarding-httproute
    kind: HTTPRoute
  policyRef:
    name: http-basic-authentication-flex
  config:
    username: "hr-admin"
    password: "secure-password-123"
    realm: "Employee Onboarding API"
    errorResponseSettings:
      statusCode: 401
      headers:
        WWW-Authenticate: 'Basic realm="Employee Onboarding API"'
        Content-Type: "application/json"
      body: |
        {
          "error": "Authentication Required",
          "message": "Please provide valid credentials to access the Employee Onboarding API",
          "code": "AUTH_001"
        }
