# Flex Gateway Rate Limiting Policy Configuration
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: employee-onboarding-rate-limit
  namespace: default
spec:
  targetRef:
    name: employee-onboarding-httproute
    kind: HTTPRoute
  policyRef:
    name: rate-limiting-flex
  config:
    rateLimits:
      - rules:
          - paths:
              - path: /broker/onboard
                method: POST
              - path: /mcp/postgres
                method: POST
              - path: /mcp/assets
                method: POST
              - path: /mcp/notifications
                method: POST
        configurations:
          - requestRate:
              requests: 1000
              period: 1m
            requestBurstSize: 5
            quotaStrategy: ROLLING_WINDOW
          - requestRate:
              requests: 100
              period: 1h
            quotaStrategy: FIXED_WINDOW
        clusterBy:
          - type: CLIENT_IP_ADDRESS
    expose:
      headers:
        - x-ratelimit-limit
        - x-ratelimit-remaining
        - x-ratelimit-reset
    response:
      statusCode: 429
      body: |
        {
          "error": "Rate limit exceeded",
          "message": "Too many requests. Please try again later.",
          "retryAfter": "{{ .RetryAfter }}s"
        }
      headers:
        content-type: "application/json"
        retry-after: "{{ .RetryAfter }}"
